on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Build
        run: bash tools/makemake && make clean && make
      - name: Run partial test suite
        run: |
          cat tests/??-* tests/180-ezmlm-gate > mytests.sh
          bash mytests.sh
