on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]

permissions: {}

jobs:
  test:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tag=infra
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Build
        run: bash tools/makemake && make clean && make && make man
      - name: Run test suite
        run: ./ezmlm-test
